name: Build and Update

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'  # src 디렉토리의 변경사항에만 반응

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  # 코드 체크아웃
        uses: actions/checkout@v2

      - name: Set up Docker Buildx  # Docker Buildx 설정
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub  # DockerHub 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # DockerHub 사용자 이름
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # DockerHub 토큰

      - name: Build and push Docker image  # 이미지 빌드 및 푸시
        uses: docker/build-push-action@v2
        with:
          context: ./src  # 빌드 컨텍스트
          push: true  # 이미지 푸시 활성화
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitops-demo:${{ github.sha }}  # 이미지 태그 (커밋 SHA 사용)
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Kubernetes manifests
        run:
          # 새 이미지 태그로 deployment.yaml 파일 업데이트
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/gitops-demo:${{ github.sha }}|g" apps/sample-app/deployment.yaml
    
          # Git 설정
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
    
          # 변경사항 커밋 및 푸시
          git add apps/sample-app/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
          git push
